# Generated by Django 5.2.6 on 2025-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='contact',
            field=models.URLField(blank=True, null=True),
        ),
    ]
