# Generated by Django 5.2.6 on 2025-09-17 13:34

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModeslByFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('workshop', 'Workshops'), ('partner', 'Partners'), ('speaker', 'Speakers')], default='partner', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='workshop',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='app_models.speaker'),
        ),
    ]
