# Generated by Django 5.2.6 on 2025-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
