# Generated by Django 5.2.6 on 2025-09-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sessions',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='week',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_models.registration')),
            ],
        ),
    ]
