# Generated by Django 5.2.6 on 2025-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speaker',
            name='unique_speaker_fullinfo',
        ),
        migrations.AddField(
            model_name='speaker',
            name='contact',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
