# Generated by Django 5.2.6 on 2025-09-17 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0002_uploadmodeslbyfile_alter_workshop_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodeslbyfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
