# Generated by Django 5.2.6 on 2025-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0003_uploadmodeslbyfile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.SmallIntegerField(),
        ),
    ]
