# Generated by Django 5.2.6 on 2025-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0004_alter_workshop_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodeslbyfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
