# Generated by Django 5.2.6 on 2025-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0005_alter_uploadmodeslbyfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmodeslbyfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
