# Generated by Django 5.2.6 on 2025-09-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0006_alter_uploadmodeslbyfile_file_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_partner_name'),
        ),
        migrations.AddConstraint(
            model_name='speaker',
            constraint=models.UniqueConstraint(fields=('name', 'bio', 'partner'), name='unique_speaker_fullinfo'),
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_workshop_title'),
        ),
    ]
