# Generated by Django 5.2.6 on 2025-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0007_partner_unique_partner_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='speaker',
            name='unique_speaker_fullinfo',
        ),
        migrations.AddConstraint(
            model_name='speaker',
            constraint=models.UniqueConstraint(fields=('name', 'bio'), name='unique_speaker_fullinfo'),
        ),
    ]
